# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuit',
            old_name='question_text',
            new_name='tuit_text',
        ),
    ]
