# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0002_auto_20171111_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuit',
            name='creator',
            field=models.CharField(default='joald', max_length=30),
            preserve_default=False,
        ),
    ]
