# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuits', '0003_tuit_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend1', models.CharField(max_length=30)),
                ('friend2', models.CharField(max_length=30)),
            ],
        ),
    ]
